### ISSUE TITLE
Exception initializing main class error

### ISSUE THREAD

**Issue by HakuaGreat** [LeGhast/Miniaturise#7]
Greetings 
I am getting the same error as the title and the plugin will not load on my server.
I am running in the 1.21.X environment which is listed as tested.
The java version is 23.

Are there any steps I need to take?

I am Japanese and I am using Deepl to translate, so I apologize if my English looks funny!

**Comment by HakuaGreat** [comment]
add error code

org.bukkit.plugin.InvalidPluginException: Exception initializing main class `de.leghast.miniaturise.Miniaturise'
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:96) ~[spigot-api-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:145) ~[spigot-api-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:406) ~[spigot-api-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:313) ~[spigot-api-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:122) ~[spigot-api-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_21_R1.CraftServer.loadPlugins(CraftServer.java:465) ~[spigot-1.21.1-R0.1-SNAPSHOT.jar:4344-Spigot-a759b62-19bf846]
        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:236) ~[spigot-1.21.1-R0.1-SNAPSHOT.jar:4344-Spigot-a759b62-19bf846]
        at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1017) ~[spigot-1.21.1-R0.1-SNAPSHOT.jar:4344-Spigot-a759b62-19bf846]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[spigot-1.21.1-R0.1-SNAPSHOT.jar:4344-Spigot-a759b62-19bf846]
        at java.base/java.lang.Thread.run(Thread.java:1575) [?:?]
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:74) ~[?:?]
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:501) ~[?:?]
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:485) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:88) ~[spigot-api-1.21.1-R0.1-SNAPSHOT.jar:?]
        ... 9 more
Caused by: java.lang.NoSuchMethodError: 'io.papermc.paper.plugin.configuration.PluginMeta de.leghast.miniaturise.Miniaturise.getPluginMeta()'
        at de.leghast.miniaturise.Miniaturise.<init>(Miniaturise.java:36) ~[?:?]
        at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62) ~[?:?]
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:501) ~[?:?]
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:485) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:88) ~[spigot-api-1.21.1-R0.1-SNAPSHOT.jar:?]
        ... 9 more

**Comment by GhastCraftHD** [comment]
Hey there,

I am sorry that I couldn't respond sooner.

From your error message I can't quite decipher what kind of error ist happening, but from the information you provided me I'd say the problem lies in the server version. This plugin is currently not updated for 1.21 and only works in 1.20 versions.

If I have some spare time in the near future I can update the plugin and with that the error should go away. 
If you don't want to wait for that you can downgrade to 1.20 or any of the sub versions and use the plugin there.

Could you also tell me, from where you have downloaded the plugin, so I can correct the listed tested versions?

Cheers
GhastCraftHD

**Comment by HakuaGreat** [comment]
Thanks for the reply.

Understood, no problem.

I am waiting to see how long your wonderful project will work with the new version.

I will use the plugin as soon as there is a new version that is compatible with 1.21.

By the way, I downloaded the plugin from spigotMC.
